const singledata =[
   {
    "id":"kaisarnoe",
    "name":"Mac Pc",
    "company":"apple",
    "price":200999,
    "colors":[
       "#000",
       "#CDD0D0"
    ],
    "description":"The Computer is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
    "category":"computer",
    "shipping":true,
    "stock":4,
    "reviews":28,
    "stars":2.8,
    "image":[
       {
          "id":"randomid1",
          "width":1080,
          "height":650,
          "url":"https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          "filename":"prod-1.png",
          "size":1080,
          "type":"image/png"
       },
       {
          "id":"randomid2",
          "width":1080,
          "height":650,
          "url":" https://images.pexels.com/photos/1275229/pexels-photo-1275229.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          "filename":"prod-2.png",
          "size":1080,
          "type":"image/png"
       },
       {
          "id":"randomid3",
          "width":1080,
          "height":650,
          "url":" https://images.pexels.com/photos/4224099/pexels-photo-4224099.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          "filename":"prod-3.png",
          "size":1080,
          "type":"image/png"
       },
       {
          "id":"randomid4",
          "width":1080,
          "height":650,
          "url":"https://images.pexels.com/photos/1619651/pexels-photo-1619651.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          "filename":"prod-4.png",
          "size":1080,
          "type":"image/png"
       }
    ]
 },

 {
   "id":"kaisarnoa",
   "name":"iphone x",
   "company":"apple",
   "price":600000,
   "colors":[
      "#ff0000",
      "#000000",
      "#CDD0D0"
   ],
   "description":"The mobile is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
   "category":"mobile",
   "featured":true,
   "stock":5,
   "reviews":58,
   "stars":4.8,
   "image":[
      {
         "id":"randomid1",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/1275229/pexels-photo-1275229.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-1.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid2",
         "width":1080,
         "height":650,
         "url":"https://petapixel.com/assets/uploads/2021/10/iphone-13-pro-prores-review-1-800x534.jpg",
         "filename":"prod-2.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid3",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/1275229/pexels-photo-1275229.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-3.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid4",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/1275229/pexels-photo-1275229.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-4.png",
         "size":1080,
         "type":"image/png"
      }
   ]
},

{
   "id":"kaisarnob",
   "name":"samsung s20",
   "company":"samsung",
   "price":500000,
   "colors":[
      "#000",
      "#22D3EF"
   ],
   "description":"The mobile is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
   "category":"mobile",
   "shipping":true,
   "stock":10,
   "reviews":28,
   "stars":4.4,
   "image":[
      {
         "id":"randomid1",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-1.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid2",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/1275229/pexels-photo-1275229.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-2.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid3",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/4224099/pexels-photo-4224099.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-3.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid4",
         "width":1080,
         "height":650,
         "url":"https://images.pexels.com/photos/1619651/pexels-photo-1619651.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-4.png",
         "size":1080,
         "type":"image/png"
      }
   ]
},

{
   "id":"kaisarnoc",
   "name":"Dell Series",
   "company":"dell",
   "price":702899,
   "colors":[
      "#22D3EF",
      "#CDD0D0"
   ],
   "description":"The Laptop is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
   "category":"laptop",
   "stock":12,
   "reviews":28,
   "stars":4.2,
   "image":[
      {
         "id":"randomid1",
         "width":1080,
         "height":650,
         "url":"https://images.pexels.com/photos/7974/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-1.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid2",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/1275229/pexels-photo-1275229.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-2.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid3",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/4224099/pexels-photo-4224099.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-3.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid4",
         "width":1080,
         "height":650,
         "url":"https://images.pexels.com/photos/1619651/pexels-photo-1619651.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-4.png",
         "size":1080,
         "type":"image/png"
      }
   ]
},


{
   "id":"kaisarnod",
   "name":"Iphone-x",
   "company":"Iphone",
   "price":102999,
   "colors":[
      "#000000",
      "#CDD0D0"
   ],
   "description":"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Animi at dicta officia dolores harum asperiores repudiandae, accusantium quos doloremque velit ea nostrum, iusto, dolore iste? Nam aut necessitatibus consequuntur commodi.",
   "category":"mobile",
   "shipping":true,
   "stock":6,
   "reviews":28,
   "stars":3.8,
   "image":[
      {
         "id":"randomid1",
         "width":1080,
         "height":650,
         "url":"https://petapixel.com/assets/uploads/2021/10/iphone-13-pro-prores-review-1-800x534.jpg",
         "filename":"prod-1.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid2",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/1275229/pexels-photo-1275229.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-2.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid3",
         "width":1080,
         "height":650,
         "url":"https://images.pexels.com/photos/1275229/pexels-photo-1275229.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-3.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid4",
         "width":1080,
         "height":650,
         "url":"https://images.pexels.com/photos/1619651/pexels-photo-1619651.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-4.png",
         "size":1080,
         "type":"image/png"
      }
   ]
},


{
   "id":"kaisarnof",
   "name":"Macbook Pro",
   "company":"apple",
   "price":699999,
   "colors":[
      "#000000",
      "#CDD0D0"
   ],
   "description":"The Laptop is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
   "category":"laptop",
   "shipping":true,
   "stock":6,
   "reviews":12,
   "stars":4.1,
   "image":[
      {
         "id":"randomid1",
         "width":1080,
         "height":650,
         "url":"https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-1.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid2",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/1275229/pexels-photo-1275229.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-2.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid3",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/4224099/pexels-photo-4224099.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-3.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid4",
         "width":1080,
         "height":650,
         "url":"https://images.pexels.com/photos/1619651/pexels-photo-1619651.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-4.png",
         "size":1080,
         "type":"image/png"
      }
   ]
},

{
   "id":"kaisarnog",
   "name":"Asus gseries",
   "company":"asus",
   "price":509999,
   "colors":[
      "#CDD0D0",
      "#000"
   ],
   "description":"The laptop is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
   "category":"laptop",
   "shipping":true,
   "stock":6,
   "reviews":23,
   "stars":3.7,
   "image":[
      {
         "id":"randomid1",
         "width":1080,
         "height":650,
         "url":"https://images.pexels.com/photos/261662/pexels-photo-261662.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-1.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid2",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/1275229/pexels-photo-1275229.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-2.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid3",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/4224099/pexels-photo-4224099.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-3.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid4",
         "width":1080,
         "height":650,
         "url":"https://images.pexels.com/photos/1619651/pexels-photo-1619651.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-4.png",
         "size":1080,
         "type":"image/png"
      }
   ]
},


{
   "id":"kaisarnoh",
   "name":"accessories",
   "price":409999,
   "company":"lenova",
   "colors":[
      "#000",
      "#CDD0D0"
   ],
   "description":"The accessories is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
   "category":"accessories",
   "featured":true,
   "shipping":true,
   "stock":6,
   "reviews":23,
   "stars":4.2,
   "image":[
      {
         "id":"randomid1",
         "width":1080,
         "height":650,
         "url":"https://images.pexels.com/photos/3178938/pexels-photo-3178938.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-1.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid2",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/1275229/pexels-photo-1275229.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-2.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid3",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/4224099/pexels-photo-4224099.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-3.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid4",
         "width":1080,
         "height":650,
         "url":"https://images.pexels.com/photos/1619651/pexels-photo-1619651.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-4.png",
         "size":1080,
         "type":"image/png"
      }
   ]
},


{
   "id":"kaisarnoi",
   "name":"Iwatch",
   "price":109999,
   "company":"apple",
   "colors":[
      "#000000"
   ],
   "description":"This watch is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
   "category":"watch",
   "shipping":true,
   "stock":6,
   "reviews":23,
   "stars":4.6,
   "image":[
      {
         "id":"randomid1",
         "width":1080,
         "height":650,
         "url":"https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-1.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid2",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/1275229/pexels-photo-1275229.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-2.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid3",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/4224099/pexels-photo-4224099.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-3.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid4",
         "width":1080,
         "height":650,
         "url":"https://images.pexels.com/photos/1619651/pexels-photo-1619651.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-4.png",
         "size":1080,
         "type":"image/png"
      }
   ]
},

{
   "id":"kaisarnoj",
   "name":"user need",
   "company":"apple",
   "price":300099,
   "colors":[
      "#ff0000",
      "#22D3EF",
      "#000000"
   ],
   "description":"The mobile is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
   "category":"accessories",
   "stock":6,
   "reviews":23,
   "stars":4.2,
   "image":[
      {
         "id":"randomid1",
         "width":1080,
         "height":650,
         "url":"https://images.pexels.com/photos/1619651/pexels-photo-1619651.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-1.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid2",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/1275229/pexels-photo-1275229.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-2.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid3",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/4224099/pexels-photo-4224099.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-3.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid4",
         "width":1080,
         "height":650,
         "url":"https://images.pexels.com/photos/1619651/pexels-photo-1619651.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-4.png",
         "size":1080,
         "type":"image/png"
      }
   ]
},

{
   "id":"kaisarnok",
   "name":"rolex premium",
   "company":"rolex",
   "price":99999,
   "colors":[
      "#000000",
      "#CDD0D0"
   ],
   "description":"This watch is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
   "category":"watch",
   "stock":6,
   "reviews":60,
   "stars":4.8,
   "image":[
      {
         "id":"randomid1",
         "width":1080,
         "height":650,
         "url":"https://images.pexels.com/photos/1697214/pexels-photo-1697214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-1.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid2",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/1275229/pexels-photo-1275229.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-2.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid3",
         "width":1080,
         "height":650,
         "url":" https://images.pexels.com/photos/4224099/pexels-photo-4224099.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-3.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid4",
         "width":1080,
         "height":650,
         "url":"https://images.pexels.com/photos/1619651/pexels-photo-1619651.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
         "filename":"prod-4.png",
         "size":1080,
         "type":"image/png"
      }
   ]
},

{
   "id":"kaisarnol",
   "name":"Fossil-436",
   "price":311999,
   "company":"Fossil",
   "colors":[
      "#22D3EF",
      "#ff0000",
      "#000000"
   ],
   "description":"This watch is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
   "category":"watch",
   "featured":true,
   "stock":6,
   "reviews":60,
   "stars":4.4,
   "image":[
      {
         "id":"randomid1",
         "width":1080,
         "height":650,
         "url":"https://c0.wallpaperflare.com/preview/680/835/609/accessory-stylish-time-time-piece.jpg",
         "filename":"prod-1.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid2",
         "width":1080,
         "height":650,
         "url":"https://c0.wallpaperflare.com/preview/680/835/609/accessory-stylish-time-time-piece.jpg",
         "filename":"prod-2.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid3",
         "width":1080,
         "height":650,
         "url":"https://c0.wallpaperflare.com/preview/680/835/609/accessory-stylish-time-time-piece.jpg",
         "filename":"prod-3.png",
         "size":1080,
         "type":"image/png"
      },
      {
         "id":"randomid4",
         "width":1080,
         "height":650,
         "url":"https://c0.wallpaperflare.com/preview/680/835/609/accessory-stylish-time-time-piece.jpg",
         "filename":"prod-4.png",
         "size":1080,
         "type":"image/png"
      }
   ]
}


]

 export default singledata